# Name
name: IgrOS-Kernel C/C++ CI

# Triggered on push
on: [push]

# Project jobs
jobs:

  # Prepare
  Build:

    # Name
    name: Build with CMake
    # Ubuntu
    runs-on: ubuntu-20.04

    # Environment variables
    env:
      SONAR_CLOUD_BUILD_WRAPPER_VERSION: "4.6.2.2472"

    # Strategy with languages matrix
    strategy:
      fail-fast: false
      matrix:
        arch: [ 'i386', 'x86_64' ]
        compiler: [ 'clang++', 'g++' ]

    # Job steps
    steps:

    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake ninja-build gcc clang gcc-multilib g++-multilib --fix-missing

    # Init CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: cpp

    # Init SonarCloud Wrapper
    - name: Initialize SonarCloud Wrapper
      shell: bash
      run: |
        curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o build-wrapper-linux-x86.zip
        curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux.zip
        unzip sonar-scanner-cli-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux.zip

    # Configure
    - name: Run CMake Configure
      env:
        IGROS_ARCH: ${{ matrix.arch }}
      run: |
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DIGROS_ARCH=${{ matrix.arch }} -DCMAKE_TOOLCHAIN_FILE=config/cmake/${{ matrix.compiler }}-${{ matrix.arch }}.cmake -DCMAKE_BUILD_TYPE=Release -B build/${{ matrix.arch }} -G Ninja .

    # Build
    - name: Run CMake Build
      env:
        IGROS_ARCH: ${{ matrix.arch }}
      run: |
        build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build-wrapper cmake --build build/${{ matrix.arch }} --target all --parallel

    # Install
    - name: Run CMake Install
      env:
        IGROS_ARCH: ${{ matrix.arch }}
      run: |
        cmake --install build/${{ matrix.arch }}

    # CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    # SonarCloud Wrapper analysis
    - name: Perform SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux/bin/sonar-scanner -X -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=master -Dproject.settings=sonar-project.properties

