# Name
name: IgrOS-Kernel C/C++ CI

# Triggered on push
on: [push]

# Project jobs
jobs:

  # Prepare
  Build:

    # Name
    name: Build with CMake
    # Ubuntu
    runs-on: ubuntu-20.04

    # Environment variables
    env:
      SONAR_CLOUD_BUILD_WRAPPER_VERSION: "4.6.2.2472"

    # Strategy with languages matrix
    strategy:
      fail-fast: false
      matrix:
        arch: [ 'i386', 'x86_64' ]
        language: [ 'cpp' ]

    # Job steps
    steps:

    # Checkout
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install multilib for i386
    - name: Install G++ Multilib
      run: |
        sudo apt update
        sudo apt install -y gcc-multilib g++-multilib --fix-missing

    # Init CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    # Init SonarCloud Wrapper
    - name: Initialize SonarCloud Wrapper
      shell: bash
      run: |
        curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o build-wrapper-linux-x86.zip
        curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux.zip
        unzip sonar-scanner-cli-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux.zip

    # Build
    - name: Run CMake
      env:
        IGROS_ARCH: ${{ matrix.arch }}
      run: build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir ./build-wrapper ./config/script/build-$IGROS_ARCH.sh

    # CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

    # SonarCloud Wrapper analysis
    - name: Initialize SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

