# Name
name: IgrOS-Kernel C/C++ CI

# Triggered on push
on: [push]

# Project jobs
jobs:

  # Prepare
  Build:

    # Name
    name: Build with CMake
    # Ubuntu
    runs-on: ubuntu-22.04

    # Environment variables
    env:
      SONAR_CLOUD_BUILD_WRAPPER_VERSION: "4.6.2.2472"

    # Strategy with languages matrix
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        arch: [ 'i386', 'x86_64' ]
        compiler: [ 'clang++', 'g++' ]

    # Job steps
    steps:

    # Checkout
    - name: 'Checkout repository'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install dependencies
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends cmake ccache ninja-build gcc clang gcc-multilib g++-multilib

    # Init CodeQL
    - name: 'CodeQL Init'
      uses: github/codeql-action/init@v2
      with:
        languages: cpp

    # Init SonarCloud Wrapper
    - name: 'SonarCloud Init'
      shell: bash
      run: |
        curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o build-wrapper-linux-x86.zip
        curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux.zip
        unzip sonar-scanner-cli-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux.zip

    # Configure
    - name: 'CMake Configure'
      run: |
        cmake --preset="config-linux-${{ matrix.arch }}-${{ matrix.compiler }}-debug"

    # Build
    - name: 'CMake Build'
      run: |
        build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build-wrapper cmake --build --preset="build-linux-${{ matrix.arch }}-${{ matrix.compiler }}-debug" --target install

    # CodeQL analysis
    - name: 'CodeQL Analysis'
      uses: github/codeql-action/analyze@v2

    # SonarCloud Wrapper analysis
    - name: 'SonarCloud Analysis'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner-${SONAR_CLOUD_BUILD_WRAPPER_VERSION}-linux/bin/sonar-scanner -X -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=master -Dproject.settings=sonar-project.properties

