# Name
name: 'IgrOS-Kernel CI/CD'

# Triggered on push
on: [push]

# Project jobs
jobs:

  # Build Kernel
  BuildKernel:

    # Name
    name: 'Build with CMake'
    # OS
    runs-on: ubuntu-latest

    # Environment variables
    env:
      IGROS_KERNEL_DIR_BUILD: "${{ github.workspace }}/build"
      IGROS_KERNEL_DIR_INSTALL: "${{ github.workspace }}/install"
      CCACHE_CONFIGPATH: "${{ github.workspace }}/.ccache"
      CCACHE_BASEDIR: "${{ github.workspace }}/.ccache"
      CCACHE_COMPRESS: "true"
      CCACHE_COMPRESSLEVEL: "6"
      CCACHE_DIR: "${{ github.workspace }}/.ccache/ccache"
      CCACHE_LOGFILE: "${{ github.workspace }}/.ccache/ccache_log.txt"
      CCACHE_MAXSIZE: "200M"
      CLICOLOR_FORCE: "1"
      NINJA_STATUS: "[%p::%e\t%f/%t]\t"
      SONAR_CLOUD_BUILD_WRAPPER_OUTPUT: build-wrapper

    # Strategy with languages matrix
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        arch: [ 'i386', 'x86_64' ]
        compiler: [ 'clang++', 'g++' ]

    # Job steps
    steps:

    # Checkout
    - name: 'Checkout repository'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install dependencies
    - name: 'Install Dependencies'
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends ccache cmake doxygen graphviz g++-multilib gcc-multilib mtools ninja-build xorriso

    # Install Clang 16.0.0
    - name: 'Install Clang 16.0.0'
      shell: bash
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 16 all
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-16 160
        sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-16 160

    # Init SonarCloud Wrapper
    - name: 'SonarCloud Init'
      uses: SonarSource/sonarcloud-github-c-cpp@v1.3

    # Restore Build Cache
    - name: 'Restore Build Cache'
      uses: actions/cache@v3
      with:
        path: ${{ env.IGROS_KERNEL_DIR_BUILD }}
        key: build-${{ matrix.compiler }}-${{ matrix.arch }}-${{ github.sha }}
        restore-keys: |
          build-${{ matrix.compiler }}-${{ matrix.arch }}-

    # Restore CCache Cache
    - name: 'Restore CCache Cache'
      uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_BASEDIR }}
        key: ccache-${{ matrix.compiler }}-${{ matrix.arch }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ matrix.compiler }}-${{ matrix.arch }}-

    # Configure
    - name: 'CMake Configure'
      shell: bash
      run: |
        mkdir -p ${{ env.CCACHE_BASEDIR }}
        cmake --preset="config-linux-${{ matrix.compiler }}-${{ matrix.arch }}-debug"

    # Build
    - name: 'CMake Build'
      shell: bash
      run: |
        build-wrapper-linux-x86-64 --out-dir ${{ env.SONAR_CLOUD_BUILD_WRAPPER_OUTPUT }} cmake --build --preset="build-linux-${{ matrix.compiler }}-${{ matrix.arch }}-debug" --target all --parallel

    # Install
    - name: 'CMake Install'
      shell: bash
      run: |
        cmake --build --preset="build-linux-${{ matrix.compiler }}-${{ matrix.arch }}-debug" --target install

    # Kernel Artifacts
    - name: 'Kernel Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.compiler }}-${{ matrix.arch }}-kernel
        path: |
          ${{ env.IGROS_KERNEL_DIR_INSTALL }}/Debug/${{ matrix.compiler }}-${{ matrix.arch }}/iso/boot/kernel.bin
          ${{ env.IGROS_KERNEL_DIR_INSTALL }}/Debug/${{ matrix.compiler }}-${{ matrix.arch }}/kernel.iso
        retention-days: 7

    # SonarCloud Wrapper analysis
    - name: 'SonarCloud Analysis'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner --define sonar.cfamily.build-wrapper-output="${{ env.SONAR_CLOUD_BUILD_WRAPPER_OUTPUT }}" -X -Dproject.settings=sonar-project.properties

    # CCache Statistics
    - name: 'CCache Statistics'
      shell: bash
      run: |
        ccache -sv

    # CCache Log Artifacts
    - name: 'CCache Log Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.compiler }}-${{ matrix.arch }}-ccache-log
        path: ${{ env.CCACHE_LOGFILE }}
        retention-days: 3

