name: IgrOS-Kernel x86_64 C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: make
      run: ./config/script/build-x86_64.sh

    - name: SonarCloud Wrapper
      shell: bash
      run: |
        curl -L -O https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -o build-wrapper-linux-x86.zip
        build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir sonar-build-wrapper ./config/script/build-x86_64.sh

    - name: SonarCloud
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        curl -L -O https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
        unzip sonar-scanner-cli-4.6.0.2311-linux.zip
        sonar-scanner-4.6.0.2311-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=master -Dproject.settings=sonar-project.properties

